### ISSUE TITLE
New IPAD Pro version size

### ISSUE THREAD

**Issue by stephen-moss88** [wryyl/interfacelift-scraper#10]
Can we add the newest ipad size to the download options?

**Comment by benjaminheng** [comment]
@stephen-moss88 I've just added resolutions for the iPad pro 10.5" and 12.9" versions! The resolutions are named `ipad_pro_10.5` and `ipad_pro_12.9` respectively. You can download them by running the script with `python interfacelift-downloader.py ipad_pro_10.5`. Let me know if it works for you!

**Comment by benjaminheng** [comment]
I'll close the issue for now. Feel free to reopen it if necessary!
