### ISSUE TITLE
To overwrite or not to overwrite 

### ISSUE THREAD

**Issue by hakt0-r** [wryyl/interfacelift-scraper#3]
Hi,
Firstly, Love your script!

Secondly, love interface lift.

I'd like to suggest a modification/enhancement to this script such that when downloading we can indicate that if the filename already exists, don't download. This way we can keep getting what is new and not re-download what was already present.

**Comment by benjaminheng** [comment]
This is a great idea! 

I've gone ahead and implemented this in 665a9f80e64b3226c0eecb48905d819d2b93780c. By default, already downloaded files are not re-downloaded. This behavior can be disabled using the `-o` or `--overwrite` flag. Check it out!

**Comment by hakt0-r** [comment]
thanks :-)
