### ISSUE TITLE
Default resolution or no parameters supplied

### ISSUE THREAD

**Issue by hakt0-r** [wryyl/interfacelift-scraper#4]
Hi!

While I have your attention... 😃 

Executing the script without parameters means that it assumes somethings. The **resolution** parameter can be made to assume the actual resolution of the system as a default. This means less typing and more smarts. 😄 

Currently it assumes 1920 x 1080, on my iMac 27". You can use built-in Perl libraries to establish the actual resolution as the default or (on a mac) run this on the terminal to get the default monitor resolution
`system_profiler SPDisplaysDataType | grep "Resolution:" | sed "/.*: /s///"`

Hope this helps.

**Comment by hakt0-r** [comment]
here are some helpful code suggestions
https://stackoverflow.com/questions/3129322/how-do-i-get-monitor-resolution-in-python

**Comment by benjaminheng** [comment]
I'm not inclined to do resolution detection as each OS has its own platform specific implementation. It'd be pain to maintain and would add a fair amount of complexity to the code for what is arguably a minor enhancement.

**Comment by hakt0-r** [comment]
these are only suggestions mate for a really useable script. thanks.

**Comment by benjaminheng** [comment]
Thanks for the suggestions!
