### ISSUE TITLE
IOS

### ISSUE THREAD

**Issue by stephen-moss88** [wryyl/interfacelift-scraper#7]
Can we add resolutions for like iphone/ipad?

**Comment by benjaminheng** [comment]
Yup, should be able to!

**Comment by stephen-moss88** [comment]
Just finished my download of 3 of the 5 sizes I want. Looking forward to an updated copy :)

**Comment by benjaminheng** [comment]
Hey! I did a quick patch to include iDevice resolutions available on the website. I haven't merged with the master branch yet. Hopefully your sizes are available! Here's the updated file:

https://github.com/benjaminheng/interfacelift-downloader/blob/apple-products-resolutions/interfacelift-downloader.py

You can click on "Raw" on the top right to download it.

The added resolutions:

```
iphone_6_plus
iphone_6
iphone_5s
iphone_5c
iphone_5
iphone_4
iphone_4s
iphone
iphone_3g
iphone_3gs
ipad_air
ipad_4
ipad_3
ipad_retina_mini
ipad_mini
ipad_1
ipad_2
```

For example:

```
python interfacelift-downloader.py ipad_retina_mini
```

**Comment by benjaminheng** [comment]
Requested resolutions are now in master.
