### ISSUE TITLE
--list and -h does not work anymore

### ISSUE THREAD

**Issue by medienoekonom** [wryyl/interfacelift-scraper#8]
When i Try to write interfacelift-downloader -h or --list it says: 

"--list" is not a known resolution.

what to do?

**Comment by benjaminheng** [comment]
Can you copy and paste the exact command you are trying to execute? It's working on my end.

```
python interfacelift-downloader.py --list
```

**Comment by benjaminheng** [comment]
Closing, unless there's more information.
